version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 977098990663.dkr.ecr.eu-west-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t wiz-app .
      - docker tag my-docker-app:latest 977098990663.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/wiz-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push 977098990663.dkr.ecr.eu-west-1.amazonaws.com/wiz-app:latest
      - echo Build completed on `date`
